<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Dada2 - Dereplicación e Inferencia de Errores – Metabarcoding de comunidades de eucariontes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./2-dada2QAQC-Merge.html" rel="next">
<link href="./2-dada2QAQC-Prep.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-775723b94007e7b2c3a70c9020acb80b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e8c0cd74c39ddf4bd7a5563e5f10a176.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>


</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Metabarcoding de comunidades de eucariontes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Buscar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Navegación de palanca" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./sesiones.html"> 
<span class="menu-text">Sesiones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Referencias.html" aria-current="page"> 
<span class="menu-text">Lecturas recomendadas</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/taniavaldiviac/metabarcoding-webpage"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./2-dada2QAQC-Prep.html">Día 3</a></li><li class="breadcrumb-item"><a href="./2-dada2QAQC-Error.html">Dada2 - Dereplicación e Inferencia de Errores</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false">
 <span class="menu-text">Día 1</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-Zoom.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conexión a Zoom</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-Conexion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conexión al servidor</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Día 2</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0b-linux-r-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a Linux y R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-Datos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nuestros datos: eDNA de peces del Golfo de California</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-Preparacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preparación del entorno</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-Clonacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clonación de repositorio Github</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./0-FASTQ.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Archivos FASTQ: estructura y organización</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1-qaqc-cutadapt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Control de calidad y recorte de primers con Cutadapt</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-dada2QAQC.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción al pipeline DADA2</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Día 3</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-dada2QAQC-Prep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DADA2 — Filtrado inicial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-dada2QAQC-Error.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Dada2 - Dereplicación e Inferencia de Errores</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-dada2QAQC-Merge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dada2 - Unión de lecturas paired-end</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-dada2QAQC-Chimeras.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dada2 - Remoción de quimeras y seguimiento de lecturas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2-dada2QAQC-Taxonomy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dada2 - Asignación taxonómica y guardado de resultados</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Día 4</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3-reporte-v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis ecológico de comunidades de peces</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4-otus-vsearch.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">OTUs: agrupamiento por similitud con VSEARCH</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false">
 <span class="menu-text">Día 5</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-decontam.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Detección y remoción de contaminantes con decontam</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5-base-datos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bases de datos de referencia personalizadas</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false">
 <span class="menu-text">Lecturas recomendadas</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="false" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Referencias.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referencias</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./2-dada2QAQC-Prep.html">Día 3</a></li><li class="breadcrumb-item"><a href="./2-dada2QAQC-Error.html">Dada2 - Dereplicación e Inferencia de Errores</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Dada2 - Dereplicación e Inferencia de Errores</h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<p>Este paso tiene dos partes: primero <strong>dereplicamos</strong> las lecturas (eliminamos duplicados y contamos abundancias), luego <strong>aprendemos el modelo de error</strong> de la secuenciadora para poder distinguir errores técnicos de variantes biológicas reales.</p>
<hr>
<section id="paso-1-dereplicación" class="level2">
<h2 class="anchored" data-anchor-id="paso-1-dereplicación">Paso 1 — Dereplicación</h2>
<section id="qué-es-la-dereplicación" class="level3">
<h3 class="anchored" data-anchor-id="qué-es-la-dereplicación">¿Qué es la dereplicación?</h3>
<p>Después del filtrado, cada muestra tiene miles de lecturas — pero muchas de ellas son <strong>idénticas</strong> entre sí. La dereplicación agrupa todas las lecturas con exactamente la misma secuencia en una sola entrada, y registra cuántas veces apareció cada una (su <strong>abundancia</strong>).</p>
<p>Por ejemplo, si una muestra tiene 200,000 lecturas pero solo 15,000 secuencias únicas, la dereplicación reduce el volumen de datos de 200,000 a 15,000 entradas, cada una con su conteo de abundancia. Esto hace que los pasos siguientes (modelado de errores, inferencia de ASVs) sean mucho más rápidos sin perder ninguna información biológica.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>exists <span class="ot">&lt;-</span> <span class="fu">file.exists</span>(filtFs) <span class="sc">&amp;</span> <span class="fu">file.exists</span>(filtRs)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>filtFs <span class="ot">&lt;-</span> filtFs[exists]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>filtRs <span class="ot">&lt;-</span> filtRs[exists]</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>sample.names <span class="ot">&lt;-</span> sample.names[exists]</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>derepFs <span class="ot">&lt;-</span> <span class="fu">derepFastq</span>(filtFs, <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>derepRs <span class="ot">&lt;-</span> <span class="fu">derepFastq</span>(filtRs, <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(derepFs) <span class="ot">&lt;-</span> sample.names</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(derepRs) <span class="ot">&lt;-</span> sample.names</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="diagnóstico-de-la-dereplicación" class="level3">
<h3 class="anchored" data-anchor-id="diagnóstico-de-la-dereplicación">Diagnóstico de la dereplicación</h3>
<p>Revisamos los resultados de la primera muestra para entender qué obtenemos:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>n_unique_F     <span class="ot">&lt;-</span> <span class="fu">length</span>(derepFs[[<span class="dv">1</span>]]<span class="sc">$</span>uniques)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>total_reads_F  <span class="ot">&lt;-</span> <span class="fu">sum</span>(derepFs[[<span class="dv">1</span>]]<span class="sc">$</span>uniques)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>compression_ratio <span class="ot">&lt;-</span> <span class="fu">round</span>(n_unique_F <span class="sc">/</span> total_reads_F <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Secuencias únicas Forward: "</span>, n_unique_F)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Ratio de compresión: "</span>, compression_ratio, <span class="st">"%"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Top 5 abundancias: "</span>, <span class="fu">paste</span>(<span class="fu">head</span>(<span class="fu">sort</span>(derepFs[[<span class="dv">1</span>]]<span class="sc">$</span>uniques, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">5</span>), <span class="at">collapse =</span> <span class="st">", "</span>))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (compression_ratio <span class="sc">&lt;</span> <span class="dv">1</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"INFO: Baja diversidad (&lt; 1% únicas). Normal en muestras con especies dominantes."</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (compression_ratio <span class="sc">&gt;</span> <span class="dv">50</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Alta diversidad inusual (&gt; 50% únicas). Revisa calidad del filtrado o contaminación."</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>En nuestros datos, los resultados se ven así:</p>
<pre><code>Secuencias únicas Forward: 17428
Ratio de compresión: 7.63%
Top 5 abundancias: 70868, 15720, 12618, 10018, 9878</code></pre>
</section>
<section id="cómo-interpretar-estos-resultados" class="level3">
<h3 class="anchored" data-anchor-id="cómo-interpretar-estos-resultados">¿Cómo interpretar estos resultados?</h3>
<ul>
<li><strong>17,428 secuencias únicas</strong> de ~228,000 lecturas totales — el 7.63% son únicas, el resto son repeticiones</li>
<li><strong>Top 5 abundancias</strong>: la secuencia más abundante apareció 70,868 veces. Estas secuencias dominantes probablemente corresponden a las especies de peces más comunes en la muestra</li>
<li>El <strong>ratio de compresión del 7.63%</strong> indica diversidad moderada, lo cual es típico en muestras de eDNA marinas</li>
</ul>
<table class="caption-top table">
<colgroup>
<col style="width: 56%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Ratio de compresión</th>
<th style="text-align: left;">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt; 1%</td>
<td style="text-align: left;">Muy pocas secuencias únicas — la muestra está dominada por pocas especies</td>
</tr>
<tr class="even">
<td style="text-align: left;">1–10%</td>
<td style="text-align: left;">Rango típico para eDNA — diversidad normal con especies dominantes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10–30%</td>
<td style="text-align: left;">Alta diversidad o amplicones largos con más variación</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt; 50%</td>
<td style="text-align: left;">Inusual — posible contaminación, baja calidad de filtrado, o datos de alta diversidad (ej. suelo)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>La mayoría de las secuencias únicas con pocas lecturas (1–5) probablemente son <strong>errores de secuenciación</strong>, no especies reales. El paso siguiente (modelado de errores) se encargará de distinguirlas de las variantes biológicas verdaderas.</p>
</div>
</div>
</section>
<section id="guardar-estadísticas" class="level3">
<h3 class="anchored" data-anchor-id="guardar-estadísticas">Guardar estadísticas</h3>
<p>El pipeline guarda las estadísticas de dereplicación para todas las muestras en <code>final_data/logs/</code>:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>derep_stats <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Sample        =</span> sample.names,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Unique_seqs_F =</span> <span class="fu">sapply</span>(derepFs, <span class="cf">function</span>(x) <span class="fu">length</span>(x<span class="sc">$</span>uniques)),</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Total_reads_F =</span> <span class="fu">sapply</span>(derepFs, <span class="cf">function</span>(x) <span class="fu">sum</span>(x<span class="sc">$</span>uniques)),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Unique_seqs_R =</span> <span class="fu">sapply</span>(derepRs, <span class="cf">function</span>(x) <span class="fu">length</span>(x<span class="sc">$</span>uniques)),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Total_reads_R =</span> <span class="fu">sapply</span>(derepRs, <span class="cf">function</span>(x) <span class="fu">sum</span>(x<span class="sc">$</span>uniques))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>derep_stats<span class="sc">$</span>Compression_ratio_F <span class="ot">&lt;-</span> <span class="fu">with</span>(derep_stats,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(Unique_seqs_F <span class="sc">/</span> Total_reads_F <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>))</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>derep_stats<span class="sc">$</span>Compression_ratio_R <span class="ot">&lt;-</span> <span class="fu">with</span>(derep_stats,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">round</span>(Unique_seqs_R <span class="sc">/</span> Total_reads_R <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>))</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(derep_stats,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">file.path</span>(output_location, <span class="st">"logs"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>            <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i], <span class="st">"_derep_stats.csv"</span>)),</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
</section>
<section id="paso-2-aprender-el-modelo-de-error" class="level2">
<h2 class="anchored" data-anchor-id="paso-2-aprender-el-modelo-de-error">Paso 2 — Aprender el modelo de error</h2>
<section id="por-qué-necesitamos-un-modelo-de-error" class="level3">
<h3 class="anchored" data-anchor-id="por-qué-necesitamos-un-modelo-de-error">¿Por qué necesitamos un modelo de error?</h3>
<p>La secuenciadora Illumina comete errores al leer las bases — una A real puede leerse como C, G o T. Estos errores no son aleatorios: dependen del tipo de transición (A→C es más frecuente que A→T) y de la calidad Phred de cada posición. Si no corregimos estos errores, los confundiríamos con variantes biológicas reales y sobreestimaríamos la diversidad de nuestra muestra.</p>
<p><code>learnErrors()</code> estima las tasas de error específicas de <strong>tu</strong> run de secuenciación. Esto es importante porque cada corrida tiene un perfil de error ligeramente diferente — depende del estado del equipo, los reactivos, la densidad del cluster, etc. Por eso DADA2 no usa tasas genéricas, sino que las <strong>aprende directamente de tus datos</strong>.</p>
</section>
<section id="preparación-definir-parámetros-y-validar-datos" class="level3">
<h3 class="anchored" data-anchor-id="preparación-definir-parámetros-y-validar-datos">Preparación: definir parámetros y validar datos</h3>
<p>Antes de lanzar <code>learnErrors()</code>, el pipeline define los parámetros de entrenamiento y verifica que haya suficientes datos para construir un modelo confiable:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>nbases_target <span class="ot">&lt;-</span> <span class="fl">1e8</span>   <span class="co"># 100 millones de bases (aumentar si tienes &gt; 50 muestras)</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>max_consist   <span class="ot">&lt;-</span> <span class="dv">25</span>    <span class="co"># más iteraciones que el default (10) para forzar convergencia</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Validar datos disponibles</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>total_bases_F <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(filtFs, <span class="cf">function</span>(f) <span class="cf">if</span> (<span class="fu">file.exists</span>(f)) <span class="fu">file.info</span>(f)<span class="sc">$</span>size <span class="cf">else</span> <span class="dv">0</span>))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>total_bases_R <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">sapply</span>(filtRs, <span class="cf">function</span>(r) <span class="cf">if</span> (<span class="fu">file.exists</span>(r)) <span class="fu">file.info</span>(r)<span class="sc">$</span>size <span class="cf">else</span> <span class="dv">0</span>))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Forward disponible: ~"</span>, <span class="fu">round</span>(total_bases_F <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>), <span class="st">" MB"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Reverse disponible: ~"</span>, <span class="fu">round</span>(total_bases_R <span class="sc">/</span> <span class="fl">1e6</span>, <span class="dv">1</span>), <span class="st">" MB"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (total_bases_F <span class="sc">&lt;</span> <span class="fl">1e6</span> <span class="sc">||</span> total_bases_R <span class="sc">&lt;</span> <span class="fl">1e6</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">warning</span>(<span class="st">"Datos muy limitados (&lt; 1 MB). El modelo puede ser inestable."</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>En nuestros datos, la salida se ve así:</p>
<pre><code>Forward disponible: ~95.2 MB
Reverse disponible: ~96.1 MB</code></pre>
<p><strong>¿Qué nos dicen estos números?</strong> Los ~95 MB por dirección representan el tamaño total de los archivos FASTQ filtrados. Esto es una estimación indirecta de cuántas bases tenemos disponibles — como regla general, un archivo FASTQ de 95 MB contiene aproximadamente 100–150 millones de bases (cada base ocupa ~1 byte de secuencia más metadatos de calidad y encabezados). Con 95 MB tenemos datos más que suficientes para alcanzar nuestro objetivo de <code>nbases_target = 1e8</code> (100 millones de bases).</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>¿Cuándo preocuparte?</strong> Si ves valores menores a 1 MB, el pipeline lanza una advertencia porque no habrá suficientes bases para estimar las 12 tasas de error con precisión. Esto puede pasar cuando muchas muestras fueron descartadas en el filtrado, o cuando trabajas con un subconjunto muy pequeño de datos. En ese caso, reduce <code>nbases_target</code> (por ejemplo a <code>1e7</code>) para que DADA2 no intente usar más datos de los que existen.</p>
</div>
</div>
</section>
<section id="parámetros-clave" class="level3">
<h3 class="anchored" data-anchor-id="parámetros-clave">Parámetros clave</h3>
<p>Los parámetros que controlan el aprendizaje del modelo son:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parámetro</th>
<th style="text-align: left;">Valor</th>
<th style="text-align: left;">Qué hace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>nbases</code></td>
<td style="text-align: left;"><code>1e8</code> (100M)</td>
<td style="text-align: left;">Número de bases a usar para aprender el modelo. DADA2 toma tantas muestras como necesite para alcanzar ese total. Aumentar a <code>2e8</code> si tienes &gt; 50 muestras</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>randomize</code></td>
<td style="text-align: left;"><code>TRUE</code></td>
<td style="text-align: left;">Selecciona lecturas al azar en lugar de tomar siempre las primeras. Produce un modelo más representativo</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>multithread</code></td>
<td style="text-align: left;"><code>2</code></td>
<td style="text-align: left;">Número de núcleos a usar. Con ~30 personas en el servidor, usamos 2 para no saturarlo</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>MAX_CONSIST</code></td>
<td style="text-align: left;"><code>25</code></td>
<td style="text-align: left;">Número máximo de iteraciones del algoritmo. El default de DADA2 es 10; aquí se aumenta a 25 para garantizar convergencia</td>
</tr>
</tbody>
</table>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>errF <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>({</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">learnErrors</span>(filtFs, <span class="at">nbases =</span> nbases_target, <span class="at">randomize =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">multithread =</span> <span class="dv">2</span>, <span class="at">MAX_CONSIST =</span> max_consist, <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>}, <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"Error al aprender modelo Forward: "</span>, <span class="fu">conditionMessage</span>(e))</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>errR <span class="ot">&lt;-</span> <span class="fu">tryCatch</span>({</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">learnErrors</span>(filtRs, <span class="at">nbases =</span> nbases_target, <span class="at">randomize =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">multithread =</span> <span class="dv">2</span>, <span class="at">MAX_CONSIST =</span> max_consist, <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>}, <span class="at">error =</span> <span class="cf">function</span>(e) {</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stop</span>(<span class="st">"Error al aprender modelo Reverse: "</span>, <span class="fu">conditionMessage</span>(e))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Este paso puede tardar varios minutos dependiendo del volumen de datos y el número de núcleos disponibles. La salida en consola te da información importante sobre cómo se construyó el modelo:</p>
<pre><code>103156235 total bases in 1587019 reads from 12 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
selfConsist step 1 ............
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
   selfConsist step 8
   selfConsist step 9
   selfConsist step 10
Convergence after  10  rounds.
105668355 total bases in 1625667 reads from 13 samples will be used for learning the error rates.
Initializing error rates to maximum possible estimate.
selfConsist step 1 .............
   selfConsist step 2
   selfConsist step 3
   selfConsist step 4
   selfConsist step 5
   selfConsist step 6
   selfConsist step 7
   selfConsist step 8
   selfConsist step 9
Convergence after  9  rounds.</code></pre>
</section>
<section id="cómo-leer-esta-salida" class="level3">
<h3 class="anchored" data-anchor-id="cómo-leer-esta-salida">¿Cómo leer esta salida?</h3>
<p>Cada bloque corresponde a una dirección (Forward primero, Reverse después). Desglosemos la primera línea:</p>
<p><strong><code>103156235 total bases in 1587019 reads from 12 samples</code></strong> — DADA2 necesitaba 100 millones de bases (<code>nbases_target = 1e8</code>) y encontró 103 millones en 1.59 millones de lecturas, tomadas de 12 de nuestras muestras. No necesitó usar todas las muestras porque alcanzó el objetivo con 12. Para Reverse, necesitó 13 muestras para llegar a 105 millones — esto es normal porque las lecturas Reverse pueden tener longitudes ligeramente distintas después del filtrado.</p>
<p><strong><code>Initializing error rates to maximum possible estimate</code></strong> — El algoritmo comienza asumiendo el peor escenario: que todas las diferencias entre lecturas son errores. A partir de ahí, va refinando.</p>
<p><strong><code>selfConsist step 1 ............</code></strong> — Los puntos representan las muestras que se procesan en cada iteración. En el step 1 aparecen 12 puntos (uno por muestra usada en Forward).</p>
</section>
<section id="qué-significa-convergencia" class="level3">
<h3 class="anchored" data-anchor-id="qué-significa-convergencia">¿Qué significa “convergencia”?</h3>
<p><code>learnErrors()</code> trabaja de forma iterativa — en cada ronda:</p>
<ol type="1">
<li><strong>Estima</strong> las tasas de error con los datos actuales</li>
<li><strong>Infiere</strong> ASVs preliminares usando esas tasas</li>
<li><strong>Re-estima</strong> los errores separando las variantes reales de los errores</li>
</ol>
<p>Cuando las estimaciones dejan de cambiar significativamente entre rondas, el modelo <strong>convergió</strong> — es decir, encontró tasas de error estables que explican bien los patrones en tus datos.</p>
<p>En nuestro caso: Forward convergió en <strong>10 rondas</strong> y Reverse en <strong>9 rondas</strong>. Ambos están en el rango ideal.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 66%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Rondas</th>
<th style="text-align: left;">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">3–5</td>
<td style="text-align: left;">Convergencia muy rápida — datos de excelente calidad o poca complejidad</td>
</tr>
<tr class="even">
<td style="text-align: left;">5–15</td>
<td style="text-align: left;">Rango típico — el modelo se ajustó bien</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15–25</td>
<td style="text-align: left;">Convergencia lenta — datos complejos o ruidosos, pero el modelo es válido</td>
</tr>
<tr class="even">
<td style="text-align: left;">No converge (alcanza MAX_CONSIST)</td>
<td style="text-align: left;">Problema: aumenta <code>MAX_CONSIST</code> a 50 o revisa la calidad de tus datos</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>¿Por qué Reverse convergió más rápido que Forward?</strong> No siempre es así. A veces Reverse tarda más porque tiene mayor tasa de error, pero en nuestros datos la diferencia es mínima (10 vs 9 rondas). Lo importante es que <strong>ambos convergieron</strong> dentro del límite de <code>MAX_CONSIST = 25</code>.</p>
</div>
</div>
</section>
<section id="validación-automática-del-modelo" class="level3">
<h3 class="anchored" data-anchor-id="validación-automática-del-modelo">Validación automática del modelo</h3>
<p>Después de aprender los modelos, el pipeline valida que las tasas de error estimadas sean razonables. ¿Por qué es necesario? Porque <code>learnErrors()</code> siempre produce un resultado — incluso con datos malos — pero eso no garantiza que el modelo sea confiable. La validación revisa la <strong>matriz de errores</strong> (<code>err_out</code>) que contiene las tasas estimadas para cada tipo de transición en cada nivel de calidad.</p>
<p><strong>¿Qué es <code>err_out</code>?</strong> Es una matriz de 16 filas × 41 columnas:</p>
<ul>
<li><strong>16 filas</strong> = todas las combinaciones posibles de base real → base leída (A2A, A2C, A2G, A2T, C2A, C2C, …, T2T)</li>
<li><strong>41 columnas</strong> = los Q-scores de 0 a 40</li>
</ul>
<p>Cada celda contiene la probabilidad estimada de esa transición en ese nivel de calidad. Por ejemplo, la celda <code>[A2C, Q30]</code> dice “la probabilidad de que una A real se lea como C cuando la calidad es Q30”.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Validar modelo Forward</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(errF<span class="sc">$</span>err_out)) {</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  rn         <span class="ot">&lt;-</span> <span class="fu">rownames</span>(errF<span class="sc">$</span>err_out)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  error_rows <span class="ot">&lt;-</span> rn[<span class="fu">substr</span>(rn, <span class="dv">1</span>, <span class="dv">1</span>) <span class="sc">!=</span> <span class="fu">substr</span>(rn, <span class="dv">3</span>, <span class="dv">3</span>)]   <span class="co"># A2C, A2G, etc.</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  q_cols     <span class="ot">&lt;-</span> <span class="fu">as.integer</span>(<span class="fu">colnames</span>(errF<span class="sc">$</span>err_out))</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  hq_cols    <span class="ot">&lt;-</span> <span class="fu">which</span>(q_cols <span class="sc">&gt;=</span> <span class="dv">20</span>)                          <span class="co"># columnas Q≥20</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  err_hq  <span class="ot">&lt;-</span> errF<span class="sc">$</span>err_out[error_rows, hq_cols, drop <span class="ot">=</span> <span class="cn">FALSE</span>]</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  max_err <span class="ot">&lt;-</span> <span class="fu">max</span>(err_hq, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Tipos de transición de error: "</span>, <span class="fu">length</span>(error_rows), <span class="st">" (de 16 posibles)"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">message</span>(<span class="st">"Tasa de error máxima en Q≥20: "</span>, <span class="fu">round</span>(max_err, <span class="dv">5</span>),</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>          <span class="st">" (normal si &lt; 0.05; preocupante si &gt; 0.10)"</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (max_err <span class="sc">&gt;</span> <span class="fl">0.1</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="st">"Tasa de error &gt; 10% en Q≥20. Revisa el perfil de calidad del run."</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">message</span>(<span class="st">"Modelo de error OK."</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p><strong>¿Qué hace este código paso a paso?</strong></p>
<ol type="1">
<li><p><strong>Filtra las transiciones de error</strong> — De las 16 filas, excluye las 4 diagonales (A2A, C2C, G2G, T2T) porque representan lecturas <em>correctas</em>, no errores. Quedan <strong>12 transiciones de error</strong> reales (A2C, A2G, A2T, C2A, C2G, etc.)</p></li>
<li><p><strong>Selecciona solo calidades Q≥20</strong> — Las bases con Q &lt; 20 ya fueron eliminadas en el filtrado (<code>filterAndTrim</code>), así que las tasas de error en calidades bajas no son relevantes para nuestros datos. Evaluar solo Q≥20 evita alarmas falsas por tasas altas en bins de calidad que no usamos</p></li>
<li><p><strong>Calcula la tasa máxima</strong> — Busca el peor caso entre todas las transiciones de error en calidades altas. Si esa tasa máxima es &lt; 5%, el modelo es confiable. Si supera el 10%, algo anda mal</p></li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 57%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Tasa máxima en Q≥20</th>
<th style="text-align: left;">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">&lt; 0.01 (1%)</td>
<td style="text-align: left;">Excelente — tasas de error muy bajas en calidades altas</td>
</tr>
<tr class="even">
<td style="text-align: left;">0.01–0.05 (1–5%)</td>
<td style="text-align: left;">Normal — rango típico para datos de Illumina</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0.05–0.10 (5–10%)</td>
<td style="text-align: left;">Aceptable pero marginal — revisa los gráficos de error</td>
</tr>
<tr class="even">
<td style="text-align: left;">&gt; 0.10 (&gt;10%)</td>
<td style="text-align: left;">Problemático — una base de alta calidad tiene &gt;10% de probabilidad de ser un error. Revisa la calidad del run o el filtrado</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>¿Por qué 12 transiciones y no 16?</strong> Hay 4 bases (A, C, G, T) y cada una puede leerse como cualquiera de las 4, dando 4×4 = 16 combinaciones. Pero 4 de ellas son la base leyéndose <em>correctamente</em> (A→A, C→C, G→G, T→T). Estas tienen probabilidades cercanas a 1.0 y no representan errores, por eso se excluyen de la validación.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="paso-3-visualizar-el-modelo-de-error" class="level2">
<h2 class="anchored" data-anchor-id="paso-3-visualizar-el-modelo-de-error">Paso 3 — Visualizar el modelo de error</h2>
<p>El gráfico de errores muestra las 12 posibles transiciones (A-&gt;C, A-&gt;G, etc.). Los <strong>puntos rojos</strong> son las tasas observadas; la <strong>linea negra</strong> es el modelo ajustado. Deben seguir el mismo patrón: la tasa de error cae conforme aumenta la calidad (Q-score).</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotErrors</span>(errF, <span class="at">nominalQ =</span> <span class="cn">TRUE</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotErrors</span>(errR, <span class="at">nominalQ =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Al ejecutar estas líneas verás advertencias como estas:</p>
<pre><code>Warning messages:
1: In scale_y_log10() :
  log-10 transformation introduced infinite values.
2: Removed 164 rows containing missing values or values outside the scale range (`geom_line()`).
3: Removed 164 rows containing missing values or values outside the scale range (`geom_line()`).</code></pre>
<p><strong>Estas advertencias son normales y no indican un problema.</strong> Ocurren porque:</p>
<ul>
<li><p><strong><code>log-10 transformation introduced infinite values</code></strong> — Algunas transiciones tienen tasa de error = 0 (cero errores observados en ciertos bins de calidad). El logaritmo de 0 es −∞, y ggplot simplemente omite esos puntos del gráfico. Esto es esperado, especialmente en calidades altas donde ciertos tipos de error son extremadamente raros.</p></li>
<li><p><strong><code>Removed 164 rows containing missing values</code></strong> — Consecuencia de lo anterior: los 164 puntos con valores infinitos o ausentes se excluyen de las líneas del gráfico. El número exacto varía según tus datos, pero valores entre 100 y 300 son típicos. Que aparezca el mismo mensaje dos veces es porque <code>plotErrors()</code> dibuja dos capas de líneas (el modelo ajustado y la tasa nominal).</p></li>
</ul>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Regla práctica:</strong> si <code>plotErrors()</code> produce una gráfica visible con el patrón esperado (tasas decrecientes), las advertencias de <code>scale_y_log10</code> se pueden ignorar con confianza. Solo preocúpate si la gráfica aparece vacía o si las líneas no se dibujan en absoluto.</p>
</div>
</div>
<p>El pipeline guarda estas gráficas automáticamente en <code>final_data/logs/</code>:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">png</span>(<span class="fu">file.path</span>(output_location, <span class="st">"logs"</span>,</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i], <span class="st">"_errF.png"</span>)),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="dv">1200</span>, <span class="at">height =</span> <span class="dv">1200</span>, <span class="at">res =</span> <span class="dv">150</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">plotErrors</span>(errF, <span class="at">nominalQ =</span> <span class="cn">TRUE</span>))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>()</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="fu">png</span>(<span class="fu">file.path</span>(output_location, <span class="st">"logs"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>              <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i], <span class="st">"_errR.png"</span>)),</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">width =</span> <span class="dv">1200</span>, <span class="at">height =</span> <span class="dv">1200</span>, <span class="at">res =</span> <span class="dv">150</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">plotErrors</span>(errR, <span class="at">nominalQ =</span> <span class="cn">TRUE</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>()</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>En nuestros datos, la gráfica Forward se ve así:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="img/errF_plot.png" class="img-fluid figure-img" style="width:100.0%"></p>
<figcaption>Modelo de error Forward estimado por learnErrors(). Cada panel muestra una transición entre bases.</figcaption>
</figure>
</div>
<section id="cómo-leer-esta-gráfica" class="level3">
<h3 class="anchored" data-anchor-id="cómo-leer-esta-gráfica">Cómo leer esta gráfica</h3>
<p>La gráfica tiene <strong>16 paneles</strong> organizados en una cuadrícula de 4×4. Cada panel representa una transición entre bases — la fila indica la base real y la columna la base leída por la secuenciadora:</p>
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Cómo leer las gráficas:</strong></p>
<ul>
<li>Los <strong>puntos grises</strong> son las tasas de error <strong>observadas</strong> en tus datos, agrupadas por Q-score. El <strong>tamaño</strong> del punto indica cuántas bases hay en ese bin — puntos grandes = muchos datos (estimación confiable), puntos pequeños = pocos datos (más incertidumbre)</li>
<li>La <strong>línea negra</strong> es el modelo de error ajustado por DADA2 — lo que aprendió <code>learnErrors()</code>. Esta es la curva que DADA2 usará para corregir errores en el paso <code>dada()</code></li>
<li>La <strong>línea roja</strong> es la tasa de error teórica según la definición nominal del Q-score (Q20 = 1 error en 100 bases, Q30 = 1 en 1,000, Q40 = 1 en 10,000)</li>
<li>El <strong>eje X</strong> (Consensus quality score) va de 0 a 40 — a mayor Q-score, mayor confianza en la base</li>
<li>El <strong>eje Y</strong> (Error frequency) está en <strong>escala logarítmica</strong> — cada marca representa un cambio de 100×. Esto permite ver tanto errores frecuentes (1e-01 = 10%) como errores raros (1e-05 = 0.001%)</li>
</ul>
</div>
</div>
</section>
<section id="los-dos-tipos-de-paneles" class="level3">
<h3 class="anchored" data-anchor-id="los-dos-tipos-de-paneles">Los dos tipos de paneles</h3>
<p><strong>Diagonal (A2A, C2C, G2G, T2T):</strong> la base real y la leída son la misma — representan lecturas <em>correctas</em>. Nota que en nuestra gráfica estos paneles aparecen <strong>vacíos</strong> o con muy pocos puntos. Esto es normal: <code>plotErrors()</code> grafica la frecuencia de <em>error</em>, y una lectura correcta no es un error, así que la frecuencia es cercana a 0 (o exactamente 0, lo que genera los valores infinitos en log10 que vimos en las advertencias).</p>
<p><strong>Fuera de la diagonal (A2C, A2G, C2A, T2G, etc.):</strong> errores reales — la secuenciadora leyó una base distinta a la real. Aquí es donde debemos fijarnos. En cada panel:</p>
<ul>
<li>La tasa de error debe <strong>bajar de izquierda a derecha</strong> — a mayor calidad Phred, menos errores</li>
<li>La <strong>línea negra debe seguir los puntos grises</strong> — esto significa que el modelo se ajustó bien a los datos observados</li>
<li>La <strong>línea negra no tiene que coincidir con la línea roja</strong> — la roja asume un modelo ideal de Illumina, pero cada run tiene su propio perfil de error real</li>
</ul>
</section>
<section id="qué-vemos-en-nuestros-datos" class="level3">
<h3 class="anchored" data-anchor-id="qué-vemos-en-nuestros-datos">¿Qué vemos en nuestros datos?</h3>
<p>Mirando los paneles de error (fuera de la diagonal):</p>
<ul>
<li><strong>Tendencia decreciente clara</strong>: en todos los paneles (A2C, A2G, G2A, T2C, etc.) la tasa de error baja conforme aumenta el Q-score. Por ejemplo, en G2A la tasa cae de ~1e-02 (1%) en Q10 a ~1e-04 (0.01%) en Q35. Esto es exactamente lo que esperamos</li>
<li><strong>La línea negra sigue los puntos grises</strong>: el modelo captura bien el patrón de los datos observados. No hay paneles donde la línea se desvíe sistemáticamente de los puntos</li>
<li><strong>Puntos grandes en Q bajos</strong>: los puntos más grandes están en calidades bajas (Q &lt; 15), donde se concentran más datos de error. A calidades altas los puntos son más pequeños porque hay menos errores que contar</li>
<li><strong>Ondulaciones en la línea negra</strong>: en algunos paneles (como T2C o A2T) la línea negra tiene pequeños “brincos” en calidades intermedias. Esto es normal cuando hay pocos reads en esos bins de Q — no indica un problema si el patrón general sigue siendo decreciente</li>
<li><strong>La línea negra está por encima de la línea roja en Q altos</strong>: en varios paneles (A2C, A2T, C2T, T2C) las tasas observadas son ligeramente mayores que las teóricas en calidades altas. Esto es típico — la definición nominal del Q-score es optimista, y el perfil real de cada run difiere. Precisamente por eso DADA2 aprende su propio modelo en lugar de usar las tasas teóricas</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>¿Debo comparar Forward vs Reverse?</strong> Sí. Es normal que la gráfica Reverse tenga tasas de error ligeramente más altas (puntos grises más arriba), especialmente en Q altos. Si Reverse se ve dramáticamente peor (línea negra plana, puntos muy dispersos), considera un truncamiento más agresivo con <code>truncLen</code> en <code>filterAndTrim</code>.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="paso-4-guardar-checkpoint-después-de-learnerrors" class="level2">
<h2 class="anchored" data-anchor-id="paso-4-guardar-checkpoint-después-de-learnerrors">Paso 4 — Guardar checkpoint después de learnErrors</h2>
<p>El pipeline guarda automáticamente un checkpoint <code>.RData</code> después de <code>learnErrors()</code>. Si el script se interrumpe más adelante, puedes retomar desde aquí sin repetir el paso más lento.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(errF, errR, derepFs, derepRs, filtFs, filtRs, sample.names, primer.data, run_name, out,</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">file =</span> <span class="fu">file.path</span>(output_location, <span class="st">"rdata_output"</span>,</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i],</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"_checkpoint2_learnErrors.RData"</span>)))</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Checkpoint 2 guardado (learnErrors)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Para reanudar desde este punto en otra sesión:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">file.path</span>(output_location, <span class="st">"rdata_output"</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>               <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i], <span class="st">"_checkpoint2_learnErrors.RData"</span>)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="paso-5-inferencia-de-asvs-con-dada" class="level2">
<h2 class="anchored" data-anchor-id="paso-5-inferencia-de-asvs-con-dada">Paso 5 — Inferencia de ASVs con <code>dada()</code></h2>
<section id="qué-hace-este-paso" class="level3">
<h3 class="anchored" data-anchor-id="qué-hace-este-paso">¿Qué hace este paso?</h3>
<p>Este es el paso central de DADA2 — donde ocurre la “magia”. La función <code>dada()</code> toma las secuencias dereplicadas y el modelo de error que acabamos de aprender, y determina cuáles secuencias únicas son <strong>variantes biológicas reales</strong> (ASVs) y cuáles son <strong>errores de secuenciación</strong>.</p>
<p>El algoritmo funciona así para cada muestra:</p>
<ol type="1">
<li>Toma todas las secuencias únicas y sus abundancias (del paso de dereplicación)</li>
<li>Compara cada secuencia con las más abundantes usando el modelo de error</li>
<li>Si la diferencia entre dos secuencias es <strong>consistente</strong> con un error de secuenciación (según las tasas aprendidas), las agrupa — la menos abundante se considera un error de la más abundante</li>
<li>Si la diferencia <strong>no puede explicarse</strong> por errores de secuenciación, las mantiene separadas — son ASVs distintas</li>
</ol>
<p>El resultado es un conjunto de ASVs por muestra: secuencias biológicas reales, corregidas de errores, a resolución de nucleótido único.</p>
</section>
<section id="ejecutar-la-inferencia" class="level3">
<h3 class="anchored" data-anchor-id="ejecutar-la-inferencia">Ejecutar la inferencia</h3>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>dadaFs <span class="ot">&lt;-</span> <span class="fu">dada</span>(derepFs, <span class="at">err =</span> errF, <span class="at">multithread =</span> <span class="dv">2</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dadaRs <span class="ot">&lt;-</span> <span class="fu">dada</span>(derepRs, <span class="at">err =</span> errR, <span class="at">multithread =</span> <span class="dv">2</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Al finalizar verás para cada muestra un resumen como este:</p>
<pre><code>Sample 1 - 228534 reads in 17428 unique sequences.
Sample 2 - 175230 reads in 14302 unique sequences.
...</code></pre>
</section>
<section id="explorar-los-resultados" class="level3">
<h3 class="anchored" data-anchor-id="explorar-los-resultados">Explorar los resultados</h3>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen de la primera muestra</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>dadaFs[[<span class="dv">1</span>]]</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>La salida te muestra cuántas ASVs se infirieron de cuántas secuencias únicas. Por ejemplo:</p>
<pre><code>dada-class: object describing DADA2 denoising results
126 sequence variants were inferred from 17428 input unique sequences.</code></pre>
<p>Esto significa que de las 17,428 secuencias únicas que tenía la muestra 1 después de la dereplicación, DADA2 determinó que solo <strong>126 son variantes biológicas reales</strong>. Las otras ~17,300 son errores de secuenciación de esas 126.</p>
</section>
<section id="cómo-interpretar-el-número-de-asvs" class="level3">
<h3 class="anchored" data-anchor-id="cómo-interpretar-el-número-de-asvs">¿Cómo interpretar el número de ASVs?</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 27%">
<col style="width: 11%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Secuencias únicas</th>
<th style="text-align: left;">ASVs inferidas</th>
<th style="text-align: left;">Ratio</th>
<th style="text-align: left;">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">17,428</td>
<td style="text-align: left;">126</td>
<td style="text-align: left;">0.7%</td>
<td style="text-align: left;">Típico — la mayoría de las secuencias únicas son errores</td>
</tr>
<tr class="even">
<td style="text-align: left;">5,000</td>
<td style="text-align: left;">200</td>
<td style="text-align: left;">4%</td>
<td style="text-align: left;">Mayor proporción de variantes reales — posible alta diversidad</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20,000</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">0.1%</td>
<td style="text-align: left;">Muy pocas ASVs — muestra dominada por pocas especies</td>
</tr>
<tr class="even">
<td style="text-align: left;">10,000</td>
<td style="text-align: left;">5,000</td>
<td style="text-align: left;">50%</td>
<td style="text-align: left;">Inusual — revisa el modelo de error o la calidad del filtrado</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>¿Por qué tan pocas ASVs?</strong> En eDNA de peces con el marcador 12S, es normal obtener entre 50 y 200 ASVs por muestra. La mayoría de las secuencias únicas en la dereplicación son variantes con 1-2 bases de diferencia respecto a una ASV abundante — exactamente el tipo de error que el modelo de <code>learnErrors()</code> aprendió a reconocer. El denoising las “colapsa” de vuelta a la secuencia original.</p>
</div>
</div>
<hr>
</section>
</section>
<section id="paso-6-guardar-checkpoint-después-de-dada" class="level2">
<h2 class="anchored" data-anchor-id="paso-6-guardar-checkpoint-después-de-dada">Paso 6 — Guardar checkpoint después de dada()</h2>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">save</span>(dadaFs, dadaRs, derepFs, derepRs, errF, errR, sample.names, primer.data, run_name, out,</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">file =</span> <span class="fu">file.path</span>(output_location, <span class="st">"rdata_output"</span>,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i],</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                             <span class="st">"_checkpoint3_dada.RData"</span>)))</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Checkpoint 3 guardado (dada)"</span>)</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<p>Para reanudar desde este punto antes de <code>mergePairs()</code>:</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="fu">file.path</span>(output_location, <span class="st">"rdata_output"</span>,</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>               <span class="fu">paste0</span>(run_name, <span class="st">"_"</span>, primer.data<span class="sc">$</span>locus_shorthand[i], <span class="st">"_checkpoint3_dada.RData"</span>)))</span></code></pre></div><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<hr>
</section>
<section id="retención-esperada-en-este-paso" class="level2">
<h2 class="anchored" data-anchor-id="retención-esperada-en-este-paso">Retención esperada en este paso</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 71%">
</colgroup>
<thead>
<tr class="header">
<th>Paso</th>
<th>Lectura típica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lecturas únicas tras dereplicación</td>
<td>5-30% del total (normal)</td>
</tr>
<tr class="even">
<td>ASVs inferidos vs únicos entrada</td>
<td>1-10% (alta compresión es buena senal)</td>
</tr>
</tbody>
</table>
<hr>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Recuerda
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><code>learnErrors()</code> necesita suficientes datos (al menos varios MB de FASTQ filtrados) para estimar tasas confiables.</li>
<li>Si el modelo no converge, aumenta <code>MAX_CONSIST</code> a 50 o <code>nbases_target</code> a <code>2e8</code>.</li>
<li>Los modelos <code>errF</code> y <code>errR</code> son independientes: las lecturas Reverse suelen tener tasas de error ligeramente mayores que las Forward, y eso es normal.</li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Para el curso
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Revisa <code>plotErrors()</code> - ¿Los puntos grises siguen la linea negra?</li>
<li>Compara el número de ASVs inferidos con el número de secuencias únicas de entrada.</li>
<li>¿Hay alguna muestra con muy pocos ASVs? ¿Coincide con las que tenian baja retención en filterAndTrim?</li>
</ol>
</div>
</div>
<hr>
<p><a href="./2-dada2QAQC-Chimeras.html" class="btn btn-primary">→ Siguiente: DADA2 — Remoción de quimeras y seguimiento de lecturas</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation column-page-right">
  <div class="nav-page nav-page-previous">
      <a href="./2-dada2QAQC-Prep.html" class="pagination-link" aria-label="DADA2 — Filtrado inicial">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">DADA2 — Filtrado inicial</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./2-dada2QAQC-Merge.html" class="pagination-link" aria-label="Dada2 - Unión de lecturas paired-end">
        <span class="nav-page-text">Dada2 - Unión de lecturas paired-end</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Dra. Tania Valdivia Carrillo — Todos los derechos reservados</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>