project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "slides/*.qmd"
    - "!**/*.ipynb"   # ← ignora notebooks
    - "!**/*.py"      # ← ignora scripts Python

website:
  repo-url: https://github.com/taniavaldiviac/metabarcoding-webpage
  title: "Metabarcoding de comunidades de eucariontes"
  page-footer:
    left: "© Dra. Tania Valdivia Carrillo — Todos los derechos reservados"
    border: true
  navbar:
    background: primary
    foreground: light
    left:
      - href: sesiones.qmd
        text: Sesiones
      - href: Referencias.qmd
        text: Referencias
    right:
      - icon: github
        href: https://github.com/taniavaldiviac/metabarcoding-webpage

format:
  html:
    theme: [litera, styles.scss]
    toc: true
    toc-depth: 3
    number-sections: false
    page-navigation: true
    lang: es
    code-fold: true
    code-tools: true
    highlight-style: github
    df-print: paged
    page-layout: full

execute:
  freeze: auto
  enabled: false
  
resources:
  - slides/*.pdf
