project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "slides/*.qmd"
    - "!**/*.ipynb"   # ← ignora notebooks
    - "!**/*.py"      # ← ignora scripts Python

website:
  repo-url: https://github.com/taniavaldiviac/metabarcoding-webpage
  title: "Metabarcoding de comunidades de eucariontes"
  page-footer:
    left: "© Dra. Tania Valdivia Carrillo — Todos los derechos reservados"
    border: true
  navbar:
    background: primary
    foreground: light
    left:
      - href: index.qmd
        text: Sobre el curso
      - href: sesiones.qmd
        text: Sesiones
      - text: Materiales
        menu:
          - href: 0-Conexion-clonacion.qmd
            text: "Conexión al servidor"
          - href: 1-qaqc-cutadapt.qmd
            text: "QAQC y Cutadapt"
          - href: 2-dada2QAQC.qmd
            text: "DADA2"
      - href: Referencias.qmd
        text: Referencias
    right:
      - icon: github
        href: https://github.com/taniavaldiviac/metabarcoding-webpage

format:
  html:
    theme: [flatly, styles.scss]
    toc: true
    number-sections: false
    lang: es
    code-fold: show
    df-print: paged
    page-layout: full

execute:
  freeze: auto
  enabled: false
  
resources:
  - slides/*.pdf
